#!/usr/bin/env python

# Copyright (c) 2015--2020, Andrew J. Hesford
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import sys
import requests
import netifaces
import configparser

from netaddr import IPAddress, IPNetwork

_useragent = "DUIA-DNS-UPDATER/1.0"

def addrweb(timeout, v4=True):
	'''
	Returns the address (IPv4 if v4 is True, IPv6 otherwise) as seen by the
	DUIA web server. If an address is not available or no response is
	received before the given timeout (in seconds), None will be returned.

	This method consumes all connection and IP formatting errors.
	'''
	from netaddr import INET_PTON
	ipurl = f"https://{'ipv4' if v4 else 'ipv6'}.duiadns.net"
	try: r = requests.get(ipurl, headers={'User-Agent': _useragent}, timeout=timeout)
	except Exception as err:
		print(f'ERROR: unable to fetch address from {ipurl}: {err}', file=sys.stderr)
		return None

	# Convert the response to an address if possible
	try: addr = IPAddress(r.text, version=(4 if v4 else 6), flags=INET_PTON)
	except Exception as err:
		print(f'ERROR: unable to parse address from {ipurl}: {err}', file=sys.stderr)
		return None

	return str(addr)


def validate_ipv6(addr, ref=None, netmask=None):
	'''
	Convert addr, as a string representing an IPv6 address, to an IPAddress
	instance, removing an interface specifier if necessary. The IPAddress
	will be considered valid iff:

	1. The IPAddress is not private, loopback, multicast, or a v4 mapping;

	2. Either:

	   a. ref and netmask together define a valid IPv6 network, and addr is
	      in it; or

	   b. ref and netmask fail to define a valid IPv6 network;

	If the IPAddress is valid, it will be returned; otherwise, None will be
	returned.

	If addr, ref or netmask are malformed, a netaddr.AddrFormatError
	exception may be raised.
	'''
	# Remove any interface specifier and canonicalize
	ipaddr = IPAddress(addr.split('%')[0]).ipv6()

	# A list of methods that check for invalid addresses
	invalidators = [getattr(ipaddr, 'is_' + method) for method in
				['multicast', 'ipv4_mapped', 'ipv4_compat',
					'loopback', 'link_local' , 'private']]

	if any(invalid() for invalid in invalidators): return None

	# Try to ensure the address falls in the same network as ref
	if ref and netmask:
		# Netifaces uses mask/prefixlen notation; use the mask portion
		netmask = netmask.split('/')[0]
		ipnet = IPNetwork(str(ref) + '/' + netmask)
		if ipaddr not in ipnet: return None

	return ipaddr


def findipv6(timeout):
	'''
	Use the public (and perhaps temporary) IPv6 address seen by DUIA to
	select a valid and, if possible, non-temporary address on the same
	subnet as the public one.

	If no valid and suitable address can be found, return None.
	'''
	try:
		# Find and validate the address identified by DUIA
		pubaddr = validate_ipv6(addrweb(timeout, v4=False))
		if pubaddr is None: raise ValueError
	except:
		# No address, or an invalid one
		return None

	# Build a mask to check for temporary addresses, if possible
	tmpmask = getattr(netifaces, 'IN6_IFF_TEMPORARY', 0)

	# Loop through all interfaces to find possible addresses
	for iface in netifaces.interfaces():
		# Try to grab any IPv6 addresses available for this interface
		try: addrs = netifaces.ifaddresses(iface)[netifaces.AF_INET6]
		except KeyError: continue

		# Map valid addresses to interface flags
		addrmap = dict()
		for addr in addrs:
			# Skip entries with no address
			if not addr.get('addr', None): continue

			# If no netmask is provided, subvert subnet checks
			netmask = addr.get('netmask', None)

			try:
				# Validate and ensure same subnet as public address
				ip = validate_ipv6(addr['addr'], pubaddr, netmask)
				if ip is None: raise ValueError
			except:
				# Skip invalid or non-matching records
				continue

			# Map address to flags, if any
			addrmap[ip] = addr.get('flags', 0)

		# If public address is not on the interface, move on
		if pubaddr not in addrmap: continue

		# If public address is temporary, prefer first permanent one
		if addrmap[pubaddr] & tmpmask:
			for addr, flags in addrmap.items():
				if flags & tmpmask == 0: return addr

		# Default to public address if permanent or no permanents exist
		return pubaddr

	return None


def findipv4(timeout):
	'''
	Use a DUIA service to determine the public IP address of this machine.
	'''
	return addrweb(timeout, v4=True)


def postupdate(host, md5pass, timeout, ipv4=None, ipv6=None):
	'''
	Post an update of the specified host with the provided IPv4 and IPv6
	addresses. Either can be None to skip an update of the corresponding
	record.

	Returns True on success, False otherwise.
	'''
	if not (ipv4 or ipv6):
		raise ValueError('At least one of ipv4 and ipv6 must be specified')

	# Build the update URL
	if not ipv4: ipstr = 'ipv6'
	elif not ipv6: ipstr = 'ipv4'
	else: ipstr = 'ip'

	srv = f'https://{ipstr}.duiadns.net/dynamic.duia?host={host}&password={md5pass}'

	if ipv4: srv += "&ip4=" + ipv4
	if ipv6: srv += "&ip6=" + ipv6

	# Try to perform the update
	try: r = requests.get(srv, headers={'User-Agent': _useragent}, timeout=timeout)
	except Exception as err:
		print(f'ERROR: unable to submit address update: {err}', file=sys.stderr)
		return False

	return r.status_code == 200


def readcache(cache):
	'''
	Attempt to read the specified cache file as a JSON object, or else
	return an empty dictionary.

	The expected format has hostnames as keys and dictionaries as values,
	where the value dictionary has optional 'ipv4' and 'ipv6' keys with
	string values representing corresponding addresses.
	'''
	import json
	try:
		f = open(cache, 'r')
	except IOError:
		return {}

	cmap = json.load(f)
	return cmap


def writecache(cmap, cache):
	'''
	Attempt to store the cmap dictionary in the location specified by cache.
	'''
	import json
	f = open(cache, 'w')
	json.dump(cmap, f)
	f.write('\n')
	f.close()


def getaddrupdate(newaddr, cache):
	'''
	If newaddr is None or an invalid IP address, return None; if newaddr
	and cache are both equivalent IP addresses, return None; otherwise,
	return newaddr.
	'''
	from netaddr import AddrFormatError

	try: newaddr = IPAddress(newaddr)
	except AddrFormatError: return None

	try: cache = IPAddress(cache)
	except AddrFormatError: return str(newaddr)

	if newaddr == cache: return None
	return str(newaddr)


def updateEngine(config):
	'''
	Process a ConfigParser and perform a DNS update accordingly.
	'''
	dsec = 'duia'

	try:
		hostnames = config.get(dsec, 'hostname').split()
	except configparser.Error:
		print(f'ERROR: Configuration must specify at least one hostname in [{dsec}]', file=sys.stderr)
		return False

	try:
		password = config.get(dsec, 'password')
	except configparser.Error:
		print(f'ERROR: Configuration must specify password in [{dsec}]', file=sys.stderr)
		return False

	try:
		cache = config.get(dsec, 'cache')
	except configparser.Error:
		print(f'ERROR: Configuration must specify cache in [{dsec}]', file=sys.stderr)
		return False

	try:
		usev4 = config.getboolean(dsec, 'ipv4')
	except configparser.NoOptionError:
		usev4 = False
	except configparser.Error:
		print(f'ERROR: Optional ipv4 boolean in [{dsec}] incorrectly specified', file=sys.stderr)
		return False

	try:
		usev6 = config.getboolean(dsec, 'ipv6')
	except configparser.NoOptionError:
		usev6 = False
	except configparser.Error:
		print(f'ERROR: Optional ipv6 boolean in [{dsec}] incorrectly specified', file=sys.stderr)
		return False

	try:
		timeout = config.getfloat(dsec, 'timeout')
	except configparser.NoOptionError:
		timeout = 10
	except configparser.Error:
		print(f'ERROR: Optional timeout float in [{dsec}] incorrectly specified', file=sys.stderr)
		return False

	if not (usev4 or usev6):
		print(f'ERROR: At least one of ipv4 and ipv6 booleans in [{dsec}] must be true', file=sys.stderr)
		return False

	try: cachemap = readcache(cache)
	except ValueError:
		print(f'ERROR: Cache file {cache} exists but could not be parsed', file=sys.stderr)
		return False

	for hostname in hostnames:
		crec = cachemap.get(hostname, {})

		# Determine if the IPv4 and IPv6 addresses need updating
		if usev4:
			addr4 = getaddrupdate(findipv4(timeout), crec.get('ipv4', None))
		else: addr4 = None
		if usev6:
			addr6 = getaddrupdate(findipv6(timeout), crec.get('ipv6', None))
		else: addr6 = None

		hostmsg = hostname
		if addr4: hostmsg += f' (ip4: {addr4})'
		if addr6: hostmsg += f' (ip6: {addr6})'

		if not addr4 and not addr6:
			print('Update unnecessary for', hostmsg)
			continue

		# Attempt an (atomic?) update
		postresult = postupdate(hostname, password, timeout, addr4, addr6)
		if postresult:
			print('Successful update for', hostmsg)
			if addr4: crec['ipv4'] = addr4
			if addr6: crec['ipv6'] = addr6
			cachemap[hostname] = crec
		else:
			print('Update failed for', hostmsg)

	try: writecache(cachemap, cache)
	except IOError:
		print('ERROR: Could not store IP cache at location', cache, file=sys.stderr)
		return False

	return True


if __name__ == '__main__':
	if len(sys.argv) != 2:
		print(f"USAGE: {sys.argv[0]} <configuration>", file=sys.stderr)
		sys.exit(1)

	# Read the configuration file
	try:
		f = open(sys.argv[1])
		config = configparser.ConfigParser()
		config.read_file(f)
	except Exception as e:
		print(f"ERROR: Unable to process configuration {sys.argv[1]}", file=sys.stderr)
		sys.exit(1)

	if not updateEngine(config): sys.exit(1)
